name: Deploy Felsstudio

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        run: |
          cd /home/vorstieg/felsstudio
          git pull origin main
          npm install
          npm run build
          pm2 restart felsstudio
